# Copyright (C) 2025 Toit contributors
# Use of this source code is governed by an MIT-style license that can be
# found in the LICENSE file.

name: 'Discord transcript'
description: 'Create a Discord transcript.'

inputs:
  discord-token:
    description: 'The Discord bot credentials.'
    required: true
  guild-id:
    description: 'The guild id.'
    required: true
  transcript-directory:
    description: 'The directory to store the transcript.'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
