name: "discord transcript"
description: "Create a discord transcript."

inputs:
  discord-credentials:
    description: "The Discord bot credentials."
    required: true
  guild-id:
    description: "The guild id."
    required: true
  output-directory:
    description: "The directory to store the transcript."
    required: true

runs:
  using: "composite"
  steps:
    - name: Linux check
      shell: bash
      if: runner.os != 'Linux'
      run: |
        echo "This action only supports Linux."
        exit 1

    - name: Inputs
      shell: bash
      run: |
        echo "Guild ID: ${{ inputs.guild-id }}"
        echo "Output directory: ${{ inputs.output-directory }}"

    - name: Check that all required inputs are given
      shell: bash
      run: |
        set -e
        if [[ -z "${{ inputs.discord-credentials }}" ]]; then
          echo "Input discord-credentials is missing."
          exit 1
        fi
        if [[ -z "${{ inputs.guild-id }}" ]]; then
          echo "Input guild ID is missing."
          exit 1
        fi
        if [[ -z "${{ inputs.output-directory }}" ]]; then
          echo "Input output-directory is missing."
          exit 1
        fi

    - name: Install node packages.
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        npm install

    - name: Generate transcript
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        # Store the credentials in '.env'.
        echo "${{ inputs.discord-credentials }}" > .env
        # Build the javascript from the typescript.
        npm run build
        mkdir out
        # Generate the transcript.
        node dist/index.js -o out ${{ inputs.guild-id }}
        out="${{ inputs.output-directory }}"
        # If out isn't absolute, make it absolute.
        if [[ ! "$out" == /* ]]; then
          out="${{ github.workspace }}/$out"
        fi
        # Move the transcript to the output directory.
        mkdir -p "$out"
        mv out/* "$out"
