name: Update generated files

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

permissions:
  contents: write

jobs:
  update-generated-files:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Update dist
        run: |
          npm install
          npm run bundle

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Regenerate files" || echo "No changes to commit"
          git push
