# Copyright (C) 2025 Toit contributors
# Use of this source code is governed by a Zero-Clause BSD license that can
# be found in the BSD0-LICENSE file.


name: Update README

on:
  push:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Update README to given version"
        required: true
        type: string

env:
  ACTION_VERSION: ${{ github.event.inputs.version || github.event.release.tag_name || '' }}
  HASH_MARKER: '${HASH}'
  VERSION_MARKER: '${VERSION}'

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Update the README
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        run: |
          # Replace the old hash and version with the new hash and version in
          # the README.md file.
          sed 's/${{ env.HASH_MARKER }}/${{github.sha }}/g' README.md.in > README.md
          sed -i 's/${{ env.VERSION_MARKER }}/${{ env.ACTION_VERSION }}/g' README.md

          git config --local user.email "leon@toit.io"
          git config --local user.name "Toit CI"
          git commit -am "Update README"
          git push

      # Check that the README.md wasn't updated.
      # We must only change the README.md.in
      - name: README check
        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
        run: |
          if [[ -n $(git diff --name-only main..HEAD README.md) ]]; then
            echo "README.md was updated. Please update README.md.in instead."
            exit 1
          fi
